### ISSUE TITLE
Workitem chart display incorrect when two series have small values

### ISSUE THREAD

**Issue by gildorwang** [merione/public#14]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gildorwang](https://github.com/gildorwang)**
_Monday Mar 25, 2013 at 03:16 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/82_

---

https://github.com/highslide-software/highcharts.com/issues/265

![1](https://f.cloud.github.com/assets/1061388/296455/4cb7b884-94fa-11e2-89de-bec897ea6d31.png)
![2](https://f.cloud.github.com/assets/1061388/296456/4cef4dc6-94fa-11e2-9ce6-871946ced4a2.png)

**Comment by RodgeFu** [comment]
Fixed as percentage
