### ISSUE TITLE
Cleanup External libs

### ISSUE THREAD

**Issue by gildorwang** [merione/public#148]
It's currently 25.8MB including unused libs like Azure SDK 1.8 which slows down new enlistments.

**Comment by Live2Learn** [comment]
The 12.2 MB of MDS assemblies seems count for almost 50 percent.

**Comment by gildorwang** [comment]
@Live2Learn Is it possible we load them with NuGet?

**Comment by Live2Learn** [comment]
@gildorwang ,yes, we can and we did it a couple of days ago, but we reversed it recently, because the Nuget Package is only available for IS team which is not easy for other teams like Lync to try out Meri.

**Comment by Live2Learn** [comment]
Now we can refer them with Nuget again because MDS team has published official ones.

**Comment by RodgeFu** [comment]
Won't fix because the MDS nuget package is too large.
