### ISSUE TITLE
Allow user to lock a view (readonly)

### ISSUE THREAD

**Issue by gildorwang** [merione/public#16]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gildorwang](https://github.com/gildorwang)**
_Wednesday Aug 28, 2013 at 12:00 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/105_

---

And hide the un-selected counters at the same time.

**Comment by RodgeFu** [comment]
won't fix until we get the requirement
