### ISSUE TITLE
The runs stat may be unsync if runs are slow in loading

### ISSUE THREAD

**Issue by gildorwang** [merione/public#18]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gildorwang](https://github.com/gildorwang)**
_Thursday Aug 29, 2013 at 16:02 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/111_

---

**Comment by RodgeFu** [comment]
No one know what this is
