### ISSUE TITLE
The statistics tooltip will be covered in some scenario

### ISSUE THREAD

**Issue by RodgeFu** [merione/public#192]
![image](https://cloud.githubusercontent.com/assets/6038235/5244901/68872650-798f-11e4-9ceb-1c59f073796c.png)

**Comment by merione** [comment]
Hmm… How to repro it?
And can you find where the tooltip is now?

**Comment by merione** [comment]
You can repro it at https://meri.cloudapp.net/tasks/%7B%7D/d0880037-b619-4e90-86b2-17b3c1ffcc5b/workitems/#

Best regards,
Rodge

Does stress test for your service make you exhausted? Merihttp://codebox/Meri can help you. ☺
If you are bored with switching between Source Depot and Visual Studio. Janushttp://codebox/Janus can help you. ☺

From: Ken Wang (SH)
Sent: Monday, December 01, 2014 10:46 PM
To: merione/public; merione/public
Cc: Rodge Fu
Subject: RE: [public] The statistics tooltip will be covered in some scenario (#192)

Hmm… How to repro it?
And can you find where is the tooltip now?

**Comment by gildorwang** [comment]
Seems it works on my side?

![image](https://cloud.githubusercontent.com/assets/1061388/5248886/bdb2cc72-79b9-11e4-842c-c4a376793c63.png)
