### ISSUE TITLE
Issues left for run-by-run

### ISSUE THREAD

**Issue by RodgeFu** [merione/public#223]
- [x] Aggregation selection 
- [x] Error Notification 
- [x] Deletion confirmation 
- [x] Url Link (user can open the link to go to specific comparison directly) 
- [x] Increase auth token timeout to one day

**Comment by RodgeFu** [comment]
- [x] The Numeric Control will set the value as string when editing it directly
- [x] The Numeric Control will decrease when pressing Enter in another Numeric Control...

**Comment by gildorwang** [comment]
- [x] Add horizontal lines in chart
