### ISSUE TITLE
Create new endpoint for anonymous users

### ISSUE THREAD

**Issue by gildorwang** [merione/public#37]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gildorwang](https://github.com/gildorwang)**
_Tuesday Jan 21, 2014 at 04:29 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/169_

---

First step for #50 to support PowerQuery users.

**Comment by gildorwang** [comment]
<a href="https://github.com/gildorwang"><img src="https://avatars.githubusercontent.com/u/1061388?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gildorwang](https://github.com/gildorwang)**
_Monday Feb 24, 2014 at 07:51 GMT_

---

Per Sidney's comments, they don't have such requirements now.
Punt.

**Comment by RodgeFu** [comment]
No requirement
