### ISSUE TITLE
url with filter doesn't work with %20

### ISSUE THREAD

**Issue by gildorwang** [merione/public#43]
<a href="https://github.com/RodgeFu"><img src="https://avatars.githubusercontent.com/u/6038235?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RodgeFu](https://github.com/RodgeFu)**
_Friday Feb 28, 2014 at 06:10 GMT_
_Originally opened as https://github.com/gildorwang/meri2/issues/187_

---

https://meri.cloudapp.net/tasks/@RegularPerf%2020140227/ will filter all the tasks.

**Comment by RodgeFu** [comment]
This is a important feature for our user to send our a link with a collection or tasks.

**Comment by Live2Learn** [comment]
I believe it's been fixed already. See, you can access https://merione.cloudapp.net/tasks/@hdis%20task/
